### ISSUE TITLE
Metadata Update

### ISSUE THREAD

**Issue by reeshmabijosh** [jmcastagnetto/covid-19-peru-limpiar-datos-minsa#1]
Hello,
Your dataset was added to CoronaWhy (https://www.coronawhy.org/) Data Lake on Dataverse as a piece of common COVID-19 data http://datasets.coronawhy.org/dataset.xhtml?persistentId=doi:10.5072/FK2/IRD24B
Would you be willing to help with the maintenance of your dataset in Dataverse, e.g. adding the relevant metadata and keeping the dataset up-to-date? That will help to make the dataset findable and accessible for the medical science community

**Comment by jmcastagnetto** [comment]
Sure thing, I usually update this dataset every night with the most current information from open data.

In case you need it, I have another dataset culled from public sources (official communications, etc.) at: https://github.com/jmcastagnetto/covid-19-peru-data/, that is also updated daily.

**Comment by jmcastagnetto** [comment]
BTW, I have now an account on your Dataverse, username: jmcastagnetto. If you assign the dataset to my account, I can edit the metadata.
